name: devfolio
description: devfolio migrated to jaspr from flutter.
version: 0.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: any
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.10
  jaspr_builder: any
  jaspr_lints: ^0.2.0
  lints: ^5.1.1
  jaspr_test: ^0.17.0

  freezed: ^2.4.1
  json_serializable: ^6.7.1

jaspr:
  mode: static
