name: Deploy Dart App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your development branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get Dependencies
        run: dart pub get

      - name: Build Dart Web App
        run: |
          dart pub global activate webdev
          webdev build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web  # Adjust this path if your output directory differs
